- src/app/components/Button.tsx
> feat: Button 컴포넌트 수정

- src/providers/QueryProviders.tsx
- 신규 기능 추가: React Query Provider 설정
- 전역에서 React Query 기능을 사용할 수 있도록 QueryClientProvider를 설정했습니다.
- 서버 상태 관리 및 캐싱, 자동 리페치 등의 기능 사용을 위함입니다.
- src/providers/QueryProviders.tsx 파일 생성
- QueryClient 인스턴스를 생성하여 QueryClientProvider로 children을 감싸는 Provider 컴포넌트 구현
close: #21
> [Feature/issue-021] QueryClient와 QueryClientProvider 설정을 위한 Provider 컴포넌트를 생성

- src/app/layout.tsx
- 신규 기능 추가: React Query 전역 상태 관리를 위한 Provider 설정
- 앱 전체에서 React Query를 사용할 수 있도록 루트 레이아웃에 QueryProvider를 적용했습니다.
- 서버 상태 관리 및 캐싱, 리페치 기능 활용을 위함입니다.
- src/app/layout.tsx에서 QueryProvider 적용
close: #22
> [Feature/issue-020] 앱 전역에서 Tanstack Query 사용 가능하도록 루트 레이아웃에 QueryProvider 적용

- components.json
- package-lock.json
- package.json
- src/app/globals.css
- src/components/NavLink/NavLink.tsx
- src/lib/utils.ts
- 신규 기능 추가: NavLink 컴포넌트 생성 및 접근성 개선
- NavLink 컴포넌트를 새로 만들어 next/link의 반복적인 사용을 간소화
- 현재 경로 기반의 활성 상태를 판단하여 UX 개선
- aria-current="page" 속성을 통해 접근성 향상
- 커스텀 스타일 적용(className, activeClassName)을 유연하게 지원
- usePathname()을 통해 현재 경로를 추적하여 활성 상태 판별
- isActive, end(정확 일치) 조건 처리 로직 구현
- 활성 상태일 경우 activeClassName 적용
- 활성 상태일 경우 aria-current="page" 속성 적용
- 현재 페이지에 해당하는 링크가 font-bold, underline 등으로 스타일 강조됨
- 스크린 리더 등 보조 기술에서 현재 페이지임을 인식 가능
- isActive 또는 end props를 통해 명시적으로 활성화 조정 가능
close: #33
> [Feature/issue-033] NavLink 컴포넌트 구현

- components.json
- package-lock.json
- package.json
- src/app/globals.css
- src/components/button/Button.tsx
- src/lib/utils.ts
- 신규 기능 추가: 공용 Button 컴포넌트 구현
- 다양한 `variant`(primary, secondary, danger, outlined)를 지원하여 버튼 스타일을 통일성 있게 확장 가능하도록 함
- 다양한 `size`(sm, md, lg) 옵션을 추가하여 UI 일관성과 재사용성 향상
- 기본 HTML 버튼 속성 지원 (`ButtonHTMLAttributes` 상속)으로 유연성 증가
- `disabled` 상태에서 비활성화된 스타일 적용
- 커스텀 스타일 확장을 위한 `className` 지원
- `Button.tsx` 공용 컴포넌트 생성
- `variant`, `size`, `disabled`, `className`, `onClick`, 기타 HTML 속성을 포함한 공용 버튼 컴포넌트 생성
- Tailwind 클래스를 활용한 기본 스타일 적용
- `PropsWithChildren<ButtonProps>`로 children 요소 사용 가능하도록 처리
- 추후 디자인 가이드를 바탕으로 스타일 개선 예정 (`// Todo` 주석 포함)
- 다양한 스타일 및 크기의 버튼을 재사용 가능
- 예시:
```tsx
<Button variant="danger" size="lg" disabled>
삭제
</Button>
https://github.com/user-attachments/assets/8d9b33ef-f4ab-4030-95f3-df173027f13b
- 현재 스타일은 임시이며, 추후 디자인 시스템에 맞게 변경 예정
- onClick은 선택적(optional)로 처리됨
close: #30
> [Feature/issue-030] Button 컴포넌트 구현

- .prettierrc
- .vscode/settings.json
- eslint.config.mjs
- jest.setup.ts
- package.json
- public/mockServiceWorker.js
- src/app/layout.tsx
- src/components/NavLink/NavLink.md
- src/components/NavLink/NavLink.test.tsx
- src/components/NavLink/NavLink.tsx
- src/mocks/browser.ts
- src/mocks/index.ts
- src/mocks/server.ts
- src/providers/MSWComponent.tsx
- tsconfig.json
- 신규 기능 추가: NavLink 컴포넌트 테스트 작성
- 버그 수정: NavLink 컴포넌트 버그 수정
- 문서 업데이트: NavLink 컴포넌트 사용법 및 기능 설명 추가
- 컴포넌트 관련 버그 수정
- 컴포넌트 사용법과 주요 기능을 문서로 정리하여 협업 및 유지보수 편의성 증대
- 컴포넌트 동작을 보장하는 단위 테스트 작성
- aria-current 속성 부여를 isActive가 아닌 activePath가 관리하도록 변경
- NavLink.md 문서 작성
- Jest + Testing Library 기반 단위 테스트 작성 및 통과 확인
close: #34
> [Feature/issue-034] NavLink에 Link 컴포넌트의 기본 props 추가

- src/components/ButtonGroup/ButtonGroup.md
- src/components/ButtonGroup/ButtonGroup.test.tsx
- src/components/ButtonGroup/ButtonGroup.tsx
* feat: ButtonGroup 컴포넌트 개발
* test: ButtonGroup 테스트 코드 추가
* docs: ButtonpGroup 문서 추가
* chore: 스크린샷용 예제 코드 삭제
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> [Feature/issue-054] ButtonGroup 컴포넌트 개발 (#95)

- src/components/poster/Poster.md
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> docs: Poster 컴포넌트 readMe 작성

- src/components/poster/Poster.md
무엇을 위한 PR인가요? (: 뒤 설명 추가)
문서 업데이트: Poster 컴포넌트 README 작성
> [Feater/issue-032] Poster 컴포넌트 README 작성

- eslint.config.mjs
- package-lock.json
- package.json
- src/components/TimePicker/TimePicker.md
- src/components/TimePicker/TimePicker.test.tsx
- src/components/TimePicker/TimePicker.tsx
- src/components/ui/button.tsx
- src/components/ui/popover.tsx
- src/components/ui/scroll-area.tsx
* chore: eslint 수정
* chore: 의존성 설치
- ui: shadcn/ui
- Button
- PopOver
- ScrollArea
- date-fns
* feat: TimePicker 컴포넌트 추가
* feat: 시간, 분 간격  & 스타일용 prop 추가
* feat: TimePicker 데모 컴포넌트 추가
* test: TimePicker 테스트 작성
* docs: TimePicker 문서 추가
* remove: TimePicker 데모 파일 삭제
> [Featuer/issue-053] TimePicker 컴포넌트 개발(+ 문서 & 테스트 ) (#132)

- src/components/Toast/Toast.md
- src/components/Toast/Toast.test.tsx
- src/components/Toast/Toast.tsx
* feat: Toast 컴포넌트 구현
* test: Toast 컴포넌트 테스트
* docs: Toast 컴포넌트 문서 작성
* refactor: Toast 위치 커스텀 className props 추가
* test:  className props 테스트 추가
* docs:  className props 추가
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
>  [Feature/issue-067] Toast 컴포넌트 구현 및 테스트, 문서 작성 (#133)

- package.json
- src/app/globals.css
- src/app/layout.tsx
- src/components/Tabs/Tabs.md
- src/components/Tabs/Tabs.test.tsx
- src/components/Tabs/Tabs.tsx
- 신규 기능 추가: 공용 Tabs 컴포넌트 구현 
- 문서 업데이트: Tabs.md 작성 
- 기타 : Tabs 컴포넌트 테스트
- 콘텐츠 연동 가능한 재사용성 높은 탭 UI 컴포넌트 필요
- translateX 기반 밑줄 애니메이션으로 UX 향상
- 외부 상태 제어형 구조로 일관된 상태 관리 가능하게 함
- 컴포넌트 단위 테스트 및 통합 테스트 추가로 안정성 확보
- Tabs 컴포넌트 생성 (`Tabs.tsx`)
- 밑줄 이동 애니메이션 적용 (`transform + transition`)
- `activeTab`, `onTabChange` props 기반 동작
- 콘텐츠 출력 테스트 포함한 `Tabs.test.tsx` 작성
- Tabs.md 문서 작성 및 컴포넌트 사용법 정리
https://github.com/user-attachments/assets/96d799be-0708-4491-b115-44fb318b8517
- 구체적인 디자인 확정 시 스타일링 수정 필요
> [Feature/issue-066] Tabs 컴포넌트 구현 및 테스트, 문서 작성

- package-lock.json
- package.json
- src/components/ProgressBar/ProgressBar.md
- src/components/ProgressBar/ProgressBar.test.tsx
- src/components/ProgressBar/ProgressBar.tsx
신규 기능 추가: 모집 인원 대비 현재 인원 비율을 시각적으로 표현하는 ProgressBar 컴포넌트 구현
- 사용자가 전달한 current, total 값을 기반으로 백분율 계산하여 진행률 바 표시
- 스크롤에 의해 보일 때 애니메이션을 한 번만 실행하도록 처리
- 접근성 속성(role=progressbar, aria-*) 추가로 시멘틱 마크업 강화
- shouldAnimate prop으로 애니메이션 제어 가능
- ProgressBar.tsx 컴포넌트 구현
- react-intersection-observer를 활용한 스크롤 진입 감지 로직 추가
- className, shouldAnimate, aria 속성 포함
- ProgressBar.test.tsx 테스트 코드 작성 (비율 렌더링, 애니메이션 유무, aria 속성 테스트 포함)
- ProgressBar.md 문서 작성 및 사용법 정리
https://github.com/user-attachments/assets/e0e4cf31-2bd2-4a7b-a4d1-890fed6bc2ec
- useInView 훅 사용을 위해 react-intersection-observer 패키지 추가 (^9.16.0)
- 추후 디자인 시스템 확정 시 색상 및 트랜지션 커스터마이징 필요
>  [Feature/issue-139] ProgressBar 컴포넌트 구현 및 테스트, 문서 작성

- package-lock.json
- package.json
- src/components/ProgressBar/ProgressBar.md
- src/components/ProgressBar/ProgressBar.test.tsx
- src/components/ProgressBar/ProgressBar.tsx
신규 기능 추가: 모집 인원 대비 현재 인원 비율을 시각적으로 표현하는 ProgressBar 컴포넌트 구현
- 사용자가 전달한 current, total 값을 기반으로 백분율 계산하여 진행률 바 표시
- 스크롤에 의해 보일 때 애니메이션을 한 번만 실행하도록 처리
- 접근성 속성(role=progressbar, aria-*) 추가로 시멘틱 마크업 강화
- shouldAnimate prop으로 애니메이션 제어 가능
- ProgressBar.tsx 컴포넌트 구현
- react-intersection-observer를 활용한 스크롤 진입 감지 로직 추가
- className, shouldAnimate, aria 속성 포함
- ProgressBar.test.tsx 테스트 코드 작성 (비율 렌더링, 애니메이션 유무, aria 속성 테스트 포함)
- ProgressBar.md 문서 작성 및 사용법 정리
https://github.com/user-attachments/assets/e0e4cf31-2bd2-4a7b-a4d1-890fed6bc2ec
- useInView 훅 사용을 위해 react-intersection-observer 패키지 추가 (^9.16.0)
- 추후 디자인 시스템 확정 시 색상 및 트랜지션 커스터마이징 필요
> [Feature/issue-139] ProgressBar 컴포넌트 기능 구현 및 테스트, 문서

- src/components/RadioGroup/RadioGroup.md
- src/components/RadioGroup/RadioGroup.test.tsx
- src/components/RadioGroup/RadioGroup.tsx
- src/components/RadioGroup/RadioGroupContext.tsx
- src/components/RadioGroup/RadioGroupItem.tsx
- src/components/RadioGroup/index.tsx
* feat: RadioGroup 컴포넌트 개발
* test: RadioGroup 테스트 추가
* docs: RadioGroup 문서 추가
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> [Feature/issue-063] RadioGroup 컴포넌트  (& 문서, 테스트) (#149)

- src/components/common/Toast/Toast.tsx
- src/components/pages/main/MainPerformanceCard.tsx
- src/components/pages/main/MainTopFavoritesPerformances.tsx
- src/components/pages/main/MainTopGroupsPerformances.tsx
- src/components/pages/main/PerformanceWrapper.tsx
- src/components/ui/skeleton.tsx
- src/constants/queryKeys.ts
- src/hooks/performanceHooks/performanceHooks.ts
- src/mocks/handlers/performancesHandlers.ts
- src/services/performancesService.ts
- src/types/performance.ts
> [Feature/issue-212] 메인 페이지 데이터 스켈레톤 적용 및 찜 낙관적 업데이트 구현 

- src/app/globals.css
- src/app/layout.tsx
- src/components/common/NavLink/NavLink.tsx
- src/components/common/TabBar/TabBar.tsx
- src/components/icons/LikeIcon.tsx
- 신규 기능 추가: 모바일 하단 탭 바 생성
- 모바일 버전에서는 라우팅을 하단 탭 바로 시도
- 767px까지 존재하다 768px에서는 사라지도록 구현
- ```<NavLink>```컴포넌트를 사용하여 구현
- 화면 크기에 따라 선택적 렌더링
https://github.com/user-attachments/assets/22e95660-ba24-4aa8-9417-795ec4e6f211
close: #215
> [Feature/issue-215] 모바일 하단 탭 바 생성

- src/app/globals.css
- src/app/layout.tsx
- src/components/common/NavLink/NavLink.tsx
- src/components/common/TabBar/TabBar.tsx
- src/components/icons/LikeIcon.tsx
> [Feature/issue-215] 모바일 하단 탭 바 생성 

- src/app/(hasGNB)/(isLogin)/notifications/page.tsx
- src/app/notifications/page.tsx
- src/components/common/GlobalNavigationBar/GlobalNavigationBar.tsx
- src/components/pages/notifications/NotificationList.tsx
- src/constants/queryKeys.ts
- src/hooks/notificationHooks/notificationHooks.ts
- src/hooks/useInfiniteScroll/useInfiniteScroll.ts
- src/mocks/browser.ts
- src/mocks/handlers/notificationHandlers.ts
- src/services/notificationsService.ts
- src/types/api.ts
- src/types/notification.ts
- 신규 기능 추가: 알림 조회 기능 구현
- 알림 내역 조회 기능 구현
- cursor방식의 무한 스크롤 사용
- pending상태일 경우 스켈레톤 컴포넌트 렌더링
- msw를 통해 알림 조회 api 모킹
- 무한 스크롤을 위한 observer hook 구현
- 무한 스크롤을 사용하여 알림 조회 hook 구현
https://github.com/user-attachments/assets/97d2c347-91d3-48a3-b9b3-1465c2c8cc43
https://github.com/user-attachments/assets/bff4fa1d-d730-4bd1-b3cc-b112ab0fbbc8
close: #219
> [Feature/issue-219] 알림 조회 기능 구현

- src/components/common/GlobalNavigationBar/Notification.tsx
- src/components/pages/notifications/NotificationCard.tsx
- src/components/pages/notifications/NotificationList.tsx
- src/constants/queryKeys.ts
- src/hooks/notificationHooks/notificationHooks.ts
- src/mocks/handlers/notificationHandlers.ts
- src/services/notificationsService.ts
- 신규 기능 추가: 알림 전체 읽음, 전제 삭제, 개별 삭제 기능 구현
- 알림 접속시 전체 읽음 처리를 통해 종 아이콘 UI업데이트
- 알림 개별, 전체 삭제 기능 구현
- 낙관적 업데이트 수행
- 알림 접속시 useEffect를 사용하여 알림 전체 읽음 처리 api호출
- 알림 개별 및 전체 삭제 기능 구현
- 낙관적 업데이트를 통해 UI에 즉각적으로 업데이트
https://github.com/user-attachments/assets/989b9551-28ff-4a11-b094-090235d18ae5
https://github.com/user-attachments/assets/b9710c53-07b1-4c86-8c78-75c7d68a7e9d
close: #219
> [Feature/issue-219] 알림 전체 읽음, 전제 삭제, 개별 삭제 기능 구현

- src/components/common/Toast/Toast.test.tsx
> [Feature/issue-232] Toast컴포넌트 테스트코드 실패 오류 해결

- src/components/pages/main/MainPerformanceCard.tsx
- src/components/pages/main/PerformanceWrapper.tsx
> [Feature/issue-234] 메인페이지 공연 카드에 순위 추가

- package-lock.json
- package.json
- src/app/(hasGNB)/(isLogin)/reviews/managements/page.tsx
- src/components/common/Tabs/Tabs.tsx
- src/components/pages/reviews/managements/ReviewCard.tsx
- src/components/pages/reviews/managements/ReviewTabs.tsx
- src/components/pages/reviews/managements/ReviewWriteModal.tsx
- src/components/pages/reviews/managements/WritableReviews.tsx
- src/components/pages/reviews/managements/WritableReviewsContent.tsx
- src/components/pages/reviews/managements/WrittenReviews.tsx
- src/components/pages/reviews/managements/WrittenReviewsContent.tsx
- src/constants/queryKeys.ts
- src/hooks/reviewHooks/reviewHooks.ts
- src/mocks/handlers/reviewsHandlers.ts
- src/services/reviewsService.ts
- src/types/enums.ts
- src/types/reviews.ts
- 신규 기능 추가: 리뷰 작성 및 조회 기능 구현 (작성 가능한 리뷰, 작성한 리뷰 탭)
- msw 기반 API 모킹 핸들러 추가 (최근 리뷰, 작성 가능한 리뷰, 작성한 리뷰 조회 및 리뷰 작성 API)
- reviewsApi 클라이언트 API 함수 구현
- React 컴포넌트 및 훅(ReviewTabs, WritableReviews, WrittenReviews, ReviewWriteModal 등) 개발
- React Query를 활용한 무한 스크롤 페이지네이션 구현
- msw 핸들러 추가
- 리뷰 카드, 작성 가능한 리뷰 목록, 작성한 리뷰 목록, 리뷰 작성 모달 등 컴포넌트 구현
- useInfiniteWritableReviews, useInfiniteWrittenReviews, usePostWriteReview 서대로 작성 가능한 리뷰 조회, 작성한 리뷰 조회, 리뷰 작성 hook 구현
- 무한 스크롤 커스텀 훅 useInfiniteScroll 적용
- 상태 관리 및 캐시 업데이트 로직 구현 (리뷰 작성 후 writable 목록에서 해당 리뷰 대상자 제거 등)
https://github.com/user-attachments/assets/00477c18-0fff-44d9-b7fa-b510c3c4560e
https://github.com/user-attachments/assets/fff9fb6f-ce0c-4a95-a917-83588285ee87
- 추후 모달 제출 상태동안 로딩 인디케이터 등 피드백 추가
close: #229
>  [Feature/issue-229] 리뷰 작성 및 조회 기능 구현

- next.config.ts
- src/components/common/Calendar/Calendar.tsx
- src/components/common/DatePicker/DatePicker.tsx
- src/components/common/GroupCard/GroupCard.tsx
- src/components/common/SortDropdown/SortDropdown.test.tsx
- src/components/common/poster/Poster.tsx
- src/components/pages/performanceDetail/PerformanceDetailInfo.tsx
- src/components/pages/performanceDetail/PerformanceDetailSummary.tsx
- src/hooks/groupHooks/groupHooks.ts
- src/hooks/performanceHooks/performanceHooks.ts
- src/mocks/handlers/groupsHandlers.ts
- 버그 수정: lint에러 수정 및 컴포넌트 경로 오류 수정
- 리펙토링: next.config 이미지 허용 경로 추가 및 최신 권장 문법으로 변경
- build오류로 배포가 불가능하여 수정
- lint에러 수정 및 컴포넌트 경로 오류 수정
- next.config 이미지 허용 경로 추가 및 최신 권장 문법으로 변경
close: #260
> [Fix/issue-260] build 오류 수정 

- next.config.ts
- src/components/common/Calendar/Calendar.tsx
- src/components/common/DatePicker/DatePicker.tsx
- src/components/common/GroupCard/GroupCard.tsx
- src/components/common/SortDropdown/SortDropdown.test.tsx
- src/components/common/poster/Poster.tsx
- src/components/pages/performanceDetail/PerformanceDetailInfo.tsx
- src/components/pages/performanceDetail/PerformanceDetailSummary.tsx
- src/hooks/groupHooks/groupHooks.ts
- src/hooks/performanceHooks/performanceHooks.ts
- src/mocks/handlers/groupsHandlers.ts
> [Fix/issue-260] build 오류 수정

- .husky/pre-push
- src/components/pages/performances/PerformanceDatePicker.tsx
- 버그 수정:
- 이유
- 작업 내역
close: #284
> [Fix/issue-284] PerformanceDatePicker 무한 렌더링 문제 수정

- src/components/pages/PerformanceCalendar/PerformanceCalendarPage.tsx
- src/hooks/performanceHooks/performanceHooks.ts
- 리펙토링: 캘린더 페이지 데이터 페칭 수정
- conflict해결
- 이미 만들어진 hook사용
close: #283
> [Fix/issue-283] conflict오류 해결 및 캘린더 페이지 수정

- next.config.ts
- src/components/common/ButtonGroup/ButtonGroup.tsx
- src/components/common/LoadingOverlay/LoadingOverlay.tsx
- src/components/common/Modal/ModalContent.tsx
- src/components/common/ProgressBar/ProgressBar.tsx
- src/components/icons/CheckboxIcon.tsx
- src/components/pages/reviews/managements/ReviewCard.tsx
- src/components/pages/reviews/managements/ReviewCardSkeleton.tsx
- src/components/pages/reviews/managements/ReviewTabs.tsx
- src/components/pages/reviews/managements/ReviewWriteModal.tsx
- src/components/pages/reviews/managements/WritableReviews.tsx
- src/components/pages/reviews/managements/WritableReviewsContent.tsx
- src/components/pages/reviews/managements/WrittenReviews.tsx
- src/components/pages/reviews/managements/WrittenReviewsContent.tsx
- src/components/pages/reviews/managements/WrittenReviewsModal.tsx
- src/constants/groupLabels.ts
- src/constants/reviewLabels.ts
- 리펙토링: 리뷰 관리 페이지 디자인에 맞게 수정
- 디자인 적용
- 리뷰 카드 디자인 적용
- 리뷰 작성 모달 디자인 수정
- 내가 쓴 리뷰 확인 모달 구현
https://github.com/user-attachments/assets/86edcab5-7290-4462-b899-c6ab76811152
- 추후 리뷰 내용에 bad words 필터링 추가
close: #306
> [Feature/issue-306] 리뷰 관리 페이지 디자인 수정

- src/components/common/Button/Button.tsx
- src/components/common/GroupCard/GroupCard.tsx
- src/components/pages/groupsManagement/ApplicationCard/ApplicationCard.tsx
- src/constants/applicationLabels.ts
- src/types/api.ts
- src/types/application.ts
- src/utils/formatApplicationCardData.ts
- src/utils/formatGroupCardData.ts
- src/utils/genderEnumLabel.ts
- 신규 기능 추가: ApplicationCard 기능 개선 및 조건별 버튼 동작 처리
- 리펙토링: GroupCard 버튼 조건 처리 및 props 정리
- 기타: 상수 분리 및 유틸/타입 정리
- ApplicationCard에 primary/secondary 버튼이 상황별로 나타나도록 구현
- src/utils/genderEnumLabel.ts 삭제
- Button 컴포넌트 주석 삭제
- GroupCard 컴포넌트에 조건부 버튼 색상(color) 및 비활성화(disabled) 기능을 추가함으로써 사용자 역할(방장 여부, 멤버 수)에 따른 UI 제어 가능(기본값은 기존과 동일 corlor=normal, disabled=false)
- formatApplicationCardData.ts 신청한 모임, 신청서 데이터  타입 분리 및 포맷 함수 유틸화로 컴포넌트 내 로직을 간결하게 유지
- formatGroupCardData.ts 참가 중인 모임 데이터 타입만 수정
- api CursorResponse에 firstPage?: boolean; 추가
- GroupCard.tsx: buttonColor, buttonDisabled props 추가 및 조건 처리
- ApplicationCard.tsx: 신청 상태에 따른 버튼 텍스트/이벤트 분기 처리
- applicationLabels.ts: 신청 상태 관련 라벨 상수 분리
- formatApplicationCardData.ts, formatGroupCardData.ts: 데이터 포맷 유틸 함수 작성
- api.ts, application.ts: API 및 …
> [Feature/issue-302] GroupCard 및 ApplicationCard 기능 개선 및 구조 분리

- src/components/common/Button/Button.tsx
- src/components/common/GroupCard/GroupCard.tsx
- src/components/pages/groupsManagement/ApplicationCard/ApplicationCard.tsx
- src/constants/applicationLabels.ts
- src/types/api.ts
- src/types/application.ts
- src/utils/formatApplicationCardData.ts
- src/utils/formatGroupCardData.ts
- src/utils/genderEnumLabel.ts
* feat: ApplicationCard 컴포넌트 구현
* refactor: ApplicationCard의 버튼 기본값 변경
* feat: GroupCard onCardClick? 수정, 버튼컬러 및 disabled props 추가
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> [Feature/issue-302] GroupCard 및 ApplicationCard 기능 개선 및 구조 분리 (#317)

- src/app/(hasGNB)/(isLogin)/groups/managements/page.tsx
- src/components/pages/groupsManagement/ApplicationCard/ApplicationCard.tsx
- src/components/pages/groupsManagement/Applications.tsx
- src/components/pages/groupsManagement/AppliedGroups.tsx
- src/components/pages/groupsManagement/GroupsManagementsTabs.tsx
- src/components/pages/groupsManagement/JoinedGroups.tsx
- src/constants/queryKeys.ts
- src/hooks/groupsManagementsHooks/groupsManagementsHooks.ts
- src/hooks/useInfiniteScroll/useInfiniteScroll.ts
- src/services/groupsManagementsService.ts
* feat: ApplicationCard 컴포넌트 구현
* feat: 모임관리 페이지 신청 취소, 참가 확정, 모임탈퇴 기능 구현
* feat: useInfiniteScroll에 isFetchingNextPage props추가, 신청/참가중인 모임에 적용
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> [Feature/issue-185] 모임 관리 페이지 신청목록, 참가목록 구현 (#321)

- src/mocks/handlers/profileHandlers.ts
- src/services/profileService.ts
- 신규 기능 추가: 
- 버그 수정: 프로필 관련 api주소 수정
- 리펙토링:
- 문서 업데이트:
- 기타:
- 잘못된 api주소가 입력되어 서버 데이터 호출이 안됨
- api주소 수정
close: #324
> [Fix/issue-324]프로필 관련 api주소 수정

- package-lock.json
- package.json
- src/components/common/InfiniteList .tsx
- src/components/pages/main/MainPerformanceSkeletonCard.tsx
- src/components/pages/main/MainTopFavoritesPerformances.tsx
- src/components/pages/main/MainTopGroupsPerformances.tsx
- src/components/pages/main/PerformanceWrapper.tsx
- src/components/pages/notifications/NotificationCard.tsx
- src/components/pages/notifications/NotificationCardSkeleton.tsx
- src/components/pages/notifications/NotificationList.tsx
- src/components/pages/reviews/managements/ReviewWriteModal.tsx
- src/components/pages/reviews/managements/WritableReviews.tsx
- src/components/pages/reviews/managements/WrittenReviews.tsx
- src/hooks/notificationHooks/notificationHooks.ts
- src/hooks/performanceHooks/performanceHooks.ts
- src/hooks/reviewHooks/reviewHooks.ts
- src/services/reviewsService.ts
- src/types/notification.ts
- src/types/reviews.ts
> [Feature/issue-311] suspensive 라이브러리 도입

- src/components/common/GlobalNavigationBar/GlobalNavigationBar.tsx
- src/components/common/Header/Header.tsx
- src/components/common/Notification/Notification.tsx
- src/components/common/SearchInput/SearchInput.tsx
- src/lib/apiFetcher.ts
- src/stores/sseStore.ts
- src/utils/getNewAccessToken.ts
> [Feature/issue-347] 액세스 토큰 재발급 로직 함수로 분리

- src/components/common/TextareaInput/TextareaInput.tsx
- src/components/pages/performanceDetail/GroupApplyModal.tsx
- src/components/pages/performanceDetail/PerformanceDetailGroupsList.tsx
- src/components/pages/performanceDetail/PerformanceDetailGroupsOptionTabs.tsx
- src/constants/queryKeys.ts
- src/hooks/groupHooks/groupHooks.ts
- src/services/groupsService.ts
- src/types/group.ts
- 신규 기능 추가: 모임 신청 기능 구현
- 모임 신청 모달 컴포넌트 생성
- 모임 신청 api 연동
- 모임 신청 모달 컴포넌트 생성
- 로그인 시에만 가능하게 설정
- 모임 신청 api 연동
- 신청 상태에 따라 다른 toast 메세지 설정
- api 응답 올 때까지 신청, 취소 버튼 disabled 처리
- `TextareaInput` 컴포넌트 디자인 일부 수정
- textarea와 글자 수 사이 여백 수정
https://github.com/user-attachments/assets/20b8919c-8ceb-4863-908b-06e4c59bfce1
https://github.com/user-attachments/assets/c42586ae-24aa-4055-bd4a-601a49945fcc
https://github.com/user-attachments/assets/50703d2f-e70e-4ef2-9cb6-72f55cf92ecd
close: #334
> [Feature/issue-334] 모임 신청 기능 구현

- src/components/common/TextareaInput/TextareaInput.tsx
- src/components/pages/performanceDetail/GroupApplyModal.tsx
- src/components/pages/performanceDetail/PerformanceDetailGroupsList.tsx
- src/components/pages/performanceDetail/PerformanceDetailGroupsOptionTabs.tsx
- src/constants/queryKeys.ts
- src/hooks/groupHooks/groupHooks.ts
- src/services/groupsService.ts
- src/types/group.ts
* design: 임의로 추가한 반응형 css 제거
* feat: 모임 신청서 작성 모달 생성
* fix: 텍스트 인풋 텍스트 스타일 변경
* feat: 로그인한 사용자만 모임 참가 신청할 수 있도록 설정
* feat: 모임 참가 신청 api 연동
* feat: 로그인 필요할 때, 모임 신청 완료됐을 때 Toast 설정
* feat: 모임 참가 신청 toast 메세지 수정 및 에러 핸들링 추가
* chore: 모임 신청 요청 타입 이름 변경
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> [Feature/issue-334] 모임 신청 기능 구현 (#348)

- src/app/(hasGNB)/(isLogin)/groups/[groupId]/page.tsx
- src/components/pages/groupDetail/GroupInfo.tsx
- src/components/pages/groupDetail/GroupMembers.tsx
- src/components/pages/groupDetail/GroupTabs.tsx
- src/components/pages/groupDetail/GroupWrapper.tsx
- 신규 기능 추가: 모임 상세 페이지 레이아웃 설정
- 모임 상세 페이지 기본 레이아웃 설정
- 모임 상세 페이지 기본 레이아웃 설정
- 모임 상세 페이지 내부 파일 구조 설정
- 로그인 여부에 따른 선택적 렌더링
close: #356
> [Feature/issue 356] 모임 상세 페이지 레이아웃

- src/components/pages/groupDetail/GroupPosts.tsx
- src/components/pages/groupDetail/GroupTabs.tsx
- src/components/pages/groupDetail/GroupWrapper.tsx
- 신규 기능 추가: 모임 상세 페이지의 게시글 목록 추가
- 기타: develop 브랜치의 최신 변경 사항과 feature/issue-184/base 브랜치 간의 충돌을 feature/issue-184/base 브랜치에서 해결하고 커밋기록을 안남기기 위해 추가수정된 파일을 하위 브랜치에서 작업했습니다.
- 불필요한 커밋 기록을 base 브랜치에 남기지 않고, 모든 관련 변경 사항을 현재 기능 브랜치(feature/issue-184/base)에 통합하여 커밋 히스토리를 깔끔하게 유지했습니다.
-모임 상세 페이지에 게시글 목록 및 댓글 섹션 UI 구현
- 충돌 해결 및 기능 구현 변경 사항을 하나의 커밋으로 통합하여 feature/issue-184/base에 기록
> [Feature/issue-184] 모임 상세 페이지 게시글 목록 추가, base 충돌 해결

- src/app/admin/reports/page.tsx
- src/app/admin/verify/route.ts
- src/components/common/CreateReportModal/CreateReportModal.tsx
- src/components/common/CreateReportModal/ImageUpload.tsx
- src/components/pages/admin/reports/AdminCheck.tsx
- src/components/pages/admin/reports/ReportCard.tsx
- src/components/pages/admin/reports/ReportDetailCard.tsx
- src/components/pages/admin/reports/ReportDetailModal.tsx
- src/components/pages/admin/reports/ReportsMain.tsx
- src/constants/reportLabels.ts
- src/hooks/reportHooks/reportHooks.ts
- src/hooks/useGetPresignedUrl/useGetPresignedUrl.ts
- src/mocks/browser.ts
- src/mocks/handlers/reportHandlers.ts
- src/services/imagesService.ts
- src/services/reportService.ts
- src/types/enums.ts
- src/types/image.ts
- src/types/report.ts
> [Feature/issue-359] 신고 페이지, 신고 모달 구현

- src/components/common/CreateReportModal/ImageUpload.tsx
- src/components/common/GroupCard/GroupCard.tsx
- src/components/common/Modal/ModalContent.tsx
- src/components/common/PerformanceCardHeadless/PerformanceCardHeadless.tsx
- src/components/common/ProfileImage/ProfileImage.tsx
- src/components/common/SlideCard/SlideCard.tsx
- src/components/common/poster/Poster.test.tsx
- src/components/common/poster/Poster.tsx
- src/components/pages/admin/reports/ReportDetailCard.tsx
- src/components/pages/groupDetail/PostImageUploader/PostImageUploader.tsx
- src/components/pages/groupsManagement/ApplicationCard/ApplicationCard.tsx
- src/components/pages/performanceDetail/PerformanceDetailInfo.tsx
- src/components/pages/performanceDetail/PerformanceDetailSummary.tsx
- src/components/pages/reviews/managements/ReviewWriteModal.tsx
- src/lib/apiFetcher.ts
- 신규 기능 추가: apiFetcher 403에러 핸들링 구현
- 버그 수정:
- 리펙토링: 이미지 최적화, 모달 관련 스타일 수정
- 문서 업데이트:
- 기타:
- vercel 배포 환경에서 image optimization의 transform 부분 트래픽이 많이 발생
- 해당 트래픽을 줄이기 위해 반응형이 아닌 이미지들의 사이즈를 고정
- 정지된 유저 관리를 위해 403에러 핸들링 구현
- 해당 트래픽을 줄이기 위해 반응형이 아닌 이미지들의 사이즈를 고정
- 정지된 유저 관리를 위해 403에러 핸들링 구현
- Image transform 트래픽 감소 기대
- 정지된 유저는 로그아웃 상태로 변경
- 특이 사항
close: #386
> [Feature/issue-386] 이미지 최적화 및 각종 오류 수정

- src/app/(hasGNB)/(isLogin)/groups/[groupId]/edit/page.tsx
- src/components/icons/BlankIcon.tsx
- src/components/pages/groupDetail/GroupInfoCard/GroupInfoCard.tsx
- src/components/pages/groupDetail/editGroup/EditGroupWrapper.tsx
- src/components/pages/groupDetail/editGroup/NormalCategorySelector.tsx
- src/components/pages/groupDetail/editGroup/NormalDateSelector.tsx
- src/components/pages/groupDetail/editGroup/NormalDescriptionInput.tsx
- src/components/pages/groupDetail/editGroup/NormalLocationSelector.tsx
- src/components/pages/groupDetail/editGroup/NormalParticipantsInput.tsx
- src/components/pages/groupDetail/editGroup/NormalTagInput.tsx
- src/components/pages/groupDetail/editGroup/NormalTitleInput.tsx
- src/hooks/groupHooks/groupHooks.ts
- src/services/groupsService.ts
- src/types/group.ts
* feat: 모임 데이터 타입 id 추가 및 수정
* feat: 모임 정보 수정 api 커스텀훅 추가
* feat: 모임 정보 카드에 수정, 신고 모달추가
* feat: 모임 정보 수정용 컴포넌트, 아이콘 추가
* feat: 모임 정보 수정 페이지 구현
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> [Feature/issue-393] 모임 정보 수정 관련 컴포넌트 추가 및 페이지 구현 (#403)

- next.config.ts
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링: 이미지 최적화 끄기
- 문서 업데이트:
- 기타:
- vercel 사용량 초과
- 이미지 최적화 끄기
- 동작
- 특이 사항
close: #432
> [Fix/issue-432] 이미지 최적화 끄기

- src/app/(hasGNB)/performances/[performanceId]/createGroup/page.tsx
- src/components/common/BottomSheetModal/BottomSheetContent.tsx
- src/components/common/Calendar/Calendar.tsx
- src/components/common/Form/FormText.tsx
- src/components/common/PerformanceCard/PerformanceCard.tsx
- src/components/common/Toast/Toast.tsx
- src/components/common/TwoButtonModal/TwoButtonModal.style.ts
- src/components/pages/createGroup/CategorySelector.tsx
- src/components/pages/createGroup/DateSelector.tsx
- src/components/pages/createGroup/FormActions.tsx
- src/components/pages/createGroup/LocationSelector.tsx
- src/components/pages/createGroup/TagInput.tsx
- src/components/pages/favorite/FavoriteTabContainer.tsx
- src/hooks/useStyles/useStyles.tsx
- src/schema/groupsCreate.ts
- src/services/groupsService.ts
- src/types/group.ts
> Bug/issue 438/base
