FestiFriends/ff_frontend

- src/components/NavLink/NavLink.tsx
- 신규 기능 추가: NavLink 컴포넌트에 Link 기본 props 추가
- NavLink에서 next/link의 기본 props (prefetch, replace 등)를 사용할 수 있도록 타입 확장
- 사용자 입장에서 더 유연하게 링크 관련 기능 활용 가능
- NavLinkProps에 React.ComponentProps<typeof Link> 확장
- 내부 Link 컴포넌트에 전달되는 props 스프레드 적용 (...props)
- NavLink 사용 시 Link의 모든 props를 동일하게 사용할 수 있음
close: #39
> [Feature/issue-039] NavLink에 Link 컴포넌트의 기본 props 추가

- src/components/Hashtag/HashtagBadge.md
- src/components/Hashtag/HashtagBadge.test.tsx
- src/components/Hashtag/HashtagBadge.tsx
- 기타: 해시태그 base를 develop에 스쿼시 머지
해시태그 base를 develop에 스쿼시 머지
- feat: 해시태그 배지 컴포넌트 구현
- chore: props canClick을 isClickable으로 변경
- refactor: 인라인 함수 제거, select-none 추가
- [Docs/issue-035] HashtagBadge 컴포넌트 README 작성 (#80)
- [Test/issue-035] HashtagBadge 컴포넌트 테스트 코드 작성 (#79)
text-ellipsis 글자수 초과시 ... 줄여서 표시 기능 추가
close: #35
> [Feature/issue-035] HashtagBadge 컴포넌트 구현 및 테스트, 문서

- src/components/ProfileImage/ProfileImage.md
- src/components/ProfileImage/ProfileImage.test.tsx
- 신규 기능 추가: ProfileImage 컴포넌트 테스트 및 README 작성
- ProfileImage 컴포넌트의 사용법, props, 스타일, 테스트 항목 등을 문서화하여 이해도 향상
- 기본 이미지, 사이즈, 스타일 옵션 등 다양한 조건 분기를 테스트하여 안정성 확보
- ProfileImage README 문서 작성
- 기본 이미지 fallback 테스트 추가
- 커스텀 이미지 렌더링 테스트 추가
- size props 클래스 적용 테스트 (sm, md, lg, fallback 포함)
- rounded, border, className 분기 조건 테스트
close: #45
> [Feature/issue-045] ProfileImage 컴포넌트 테스트 및 문서 작성

- src/components/ReportItem/ReportItem.md
- src/components/ReportItem/ReportItem.test.tsx
- src/components/ReportItem/ReportItem.tsx
- src/constants/reportLabels.ts
- src/types/enums.ts
- src/utils/reportResonEnumLabels.ts
- 신규 기능 추가: ReportItem 컴포넌트 구현
- 테스트 코드 작성 및 문서화
- 신고 내역을 카드 형태로 보여주는 ReportItem 컴포넌트를 추가하였습니다.
- 날짜와 신고 사유를 명확하게 표현하여 UX 개선
- 클릭 이벤트를 통해 모달 또는 상세보기로 연동 가능하도록 구성
- ReportItem 컴포넌트 구현
- props: reportedAt, reason, onClick, className 추가
- 페이지내에서 신고일시 YY-MM-dd HH:mm 포맷
- 테스트 코드 작성 (@testing-library/react)
- 컴포넌트 및 테스트 문서 작성 
https://github.com/user-attachments/assets/5fff04d0-134d-4345-9539-b59af02a908c
- 날짜 포맷 유틸은 추후 date-fns 기반으로 통합 예정
- 현재는 formatDateTime 임시 함수 사용
- 추후 API 연동 시, 모달 내 상세 데이터 바인딩 예정
> [Feature/issue-135]Report item 컴포넌트 구현 및 테스트, 문서

- src/components/ReportItem/ReportItem.md
- src/components/ReportItem/ReportItem.test.tsx
- src/components/ReportItem/ReportItem.tsx
- src/constants/reportLabels.ts
- src/types/enums.ts
- src/utils/reportResonEnumLabels.ts
- 신규 기능 추가: ReportItem 컴포넌트 구현
- 테스트 코드 작성 및 문서화
- 신고 내역을 카드 형태로 보여주는 ReportItem 컴포넌트를 추가하였습니다.
- 날짜와 신고 사유를 명확하게 표현하여 UX 개선
- 클릭 이벤트를 통해 모달 또는 상세보기로 연동 가능하도록 구성
- ReportItem 컴포넌트 구현
- props: reportedAt, reason, onClick, className 추가
- 페이지내에서 신고일시 YY-MM-dd HH:mm 포맷
- 테스트 코드 작성 (@testing-library/react)
- 컴포넌트 및 테스트 문서 작성 
https://github.com/user-attachments/assets/5fff04d0-134d-4345-9539-b59af02a908c
- 날짜 포맷 유틸은 추후 date-fns 기반으로 통합 예정
- 현재는 formatDateTime 임시 함수 사용
- 추후 API 연동 시, 모달 내 상세 데이터 바인딩 예정
> [Feature/issue-168] ReportItem 컴포넌트 구현 및 테스트, 문서

- src/components/common/Toast/Toast.tsx
- src/components/pages/main/MainPerformanceCard.tsx
- src/components/pages/main/MainTopFavoritesPerformances.tsx
- src/components/pages/main/MainTopGroupsPerformances.tsx
- src/components/pages/main/PerformanceWrapper.tsx
- src/components/ui/skeleton.tsx
- src/constants/queryKeys.ts
- src/hooks/performanceHooks/performanceHooks.ts
- src/mocks/handlers/performancesHandlers.ts
- src/services/performancesService.ts
- src/types/performance.ts
- 신규 기능 추가: 메인 페이지 데이터 스켈레톤 적용 및 찜 낙관적 업데이트 구현
- 공연 목록이 서버에서 불러와질 동안 스켈레톤 컴포넌트 렌더링
- 찜 요청 시 낙관적 업데이트 수행
- tanstack-query를 통해 공연 목록을 불러올 때 isPending상태일 경우 공연 목록 카드와 동일한 크기의 스켈레톤 컴포넌트를 렌더링 하도록 변경
- tanstack-query를 사용하여 공연을 찜 했을때 실제 적용까지 오래 걸리더라도 낙관적으로 업데이트를 수행
https://github.com/user-attachments/assets/dd9796cf-6496-4c18-a102-e5c452010fba
https://github.com/user-attachments/assets/e94c8298-fa8b-4dbf-9f86-e1e24227d1a6
https://github.com/user-attachments/assets/b7b43255-1bea-4810-ba67-b9050cf27407
- 향후 배너 클릭 시 공연 상세 이동 기능 추가 예정
- 공연 카드 클릭시 라우팅 적용 예정
- 현재는 모바일 크기(가로 375px)에 맞춰진 상태로 추후 반응형 스타일링 예정
close: #212
> [Feature/issue-212] 메인 페이지 데이터 스켈레톤 적용 및 찜 낙관적 업데이트 구현

- src/components/common/GlobalNavigationBar/GlobalNavigationBar.tsx
- src/components/common/GlobalNavigationBar/Notification.tsx
- src/constants/queryKeys.ts
- src/hooks/notificationHooks/notificationHooks.ts
- src/mocks/handlers/notificationHandlers.ts
- src/services/notificationsService.ts
- src/types/notification.ts
- 신규 기능 추가: 새 알림 조회 기능 구현
- 사용자가 라우팅 시 새로운 알림이 있나 확인할 수 있도록 구현
- msw를 사용하여 api 모킹, 50%확률로 새 알림이 있거나 없도록 설정
- tanstack-query를 사용하여 상태 관리 및 리페칭
- 라우팅 주소가 바뀔때마다 해당 쿼리키 초기화
https://github.com/user-attachments/assets/a94198a9-d5ff-4742-be23-846664d19f5d
close: #219
> [Feature/issue-219] 새 알림 조회 기능 구현

- src/components/common/Toast/Toast.test.tsx
- 버그 수정: Toast컴포넌트 테스트코드 실패 오류 해결
- ```<Toast>```컴포넌트를 ```<Portal>```로 감싸면서 생긴 테스트코드 오류 해결
- 테스트코드에서 beforeAll을 통해 portal의 id에 해당하는 ```<div>```를 document.body에 appendChild를 통해 삽입
- 테스트 정상 작동
- 
close: #232
> [Feature/issue-232] Toast컴포넌트 테스트코드 실패 오류 해결

- src/components/pages/main/MainPerformanceCard.tsx
- src/components/pages/main/PerformanceWrapper.tsx
- 신규 기능 추가: 메인페이지 공연 카드에 순위 추가
- 각 공연들의 해당 카테고리에 대한 순위를 보여주기 위해 추가
- 포스터 이미지를 감싸는 ```<div>```를 생성하여 relative속성을 부여한 뒤, 자식으로 absolute속성을 부여하여 이미지 위에 표시
- before
- after
close: #234
> [Feature/issue-234] 메인페이지 공연 카드에 순위 추가

- src/mocks/server.ts
- 버그 수정: msw에서 performances/recent-reviews 가 performances/:performanceId로 매칭되는 오류
- 최근 리뷰 목록을 불러오지 못하는 오류 해결
- msw를 통해 서버에 등록하는 과정에서 reveiwsHandlers를 performancesHandlers의 상위로 변경
close: #257
> [Fix/issue-257] msw에서 performances/recent-reviews 가 performances/:performanceId로 매칭되는 오류 수정

- src/components/pages/performances/PerformancesListContainer.tsx
- src/hooks/performanceHooks/performanceHooks.ts
- src/hooks/useQueryParam/useQueryParam.ts
- 리펙토링: fetching 부분을 서버로 분리 및 관심사 분리
- 이유 
- next/fetcher가 클라이언트 사이드에서 호출되고 있어서 의미가 없음
- suspense가 제대로 동작하지 않음  
- `useGetPerformance` 훅으로 분리하여 클라이언트 사이트에서  `next/fetcher`의 호출을 방지
- 쿼리스트링을 처리하던 부분은 `useQueryParam`안에 `getPerformanceQueryString`으로 분리하여 관심사를 나눴음
- `QueryPagination` 적용
close: #265
> [Refactor/issue-265] PerformanceListContainer 리펙토링

- eslint.config.mjs
- 버그 수정: eslint import 순서 적용 안되는 이슈 해결
- eslint에 설정해둔 import 순서가 제대로 적용되지 않는 이슈 해결
- `@/**` 형식의 파일을 잘 인식하지 못해 import 순서가 뒤섞임
- `eslint.config.mjs` 파일 189번째 줄에 아래 코드 추가해여 해결
```tsx
{ pattern: '@/**', group: 'internal', position: 'before' },
```
close: #279
> [Fix/issue-279] eslint import 순서 적용 안되는 이슈 해결

- src/app/(hasGNB)/(isLogin)/groups/managements/page.tsx
- src/components/pages/groupsManagement/ApplicationCard/ApplicationCard.tsx
- src/components/pages/groupsManagement/Applications.tsx
- src/components/pages/groupsManagement/AppliedGroups.tsx
- src/components/pages/groupsManagement/GroupsManagementsTabs.tsx
- src/components/pages/groupsManagement/JoinedGroups.tsx
- src/constants/queryKeys.ts
- src/hooks/groupsManagementsHooks/groupsManagementsHooks.ts
- src/hooks/useInfiniteScroll/useInfiniteScroll.ts
- src/services/groupsManagementsService.ts
- 신규 기능 추가: 모임 참가중/신청한 모임 관리 기능 구현
- 신청한 모임, 참가 중인 모임, 받은 신청서 목록을 탭 형태로 구분하여 볼 수 있도록 기능을 추가하였습니다.
- 신청 취소 및 참가 확정 처리 기능을 구현하였고, 모임 탈퇴 기능도 추가되었습니다.
- API 요청에 따라 관련 쿼리를 invalidate하여 최신 데이터를 반영합니다.
- GroupsManagementsTabs.tsx : 탭 구조 구현
- AppliedGroups.tsx : 신청한 모임 목록 조회, 신청 취소/참가 확정 처리 기능 구현
- JoinedGroups.tsx : 참가 중인 모임 목록 조회, 탈퇴 기능 및 버튼 상태 분기 처리
- Applications.tsx : 받은 신청서 목록 구현 (기존 컴포넌트 사용)
- groupsManagementsHooks.ts : useCancelApplication, useConfirmApplication, useLeaveGroup 훅 구현
- groupsManagementsService.ts : 관련 API 요청 함수 정의
https://github.com/user-attachments/assets/8650ad21-e329-4dfa-b95b-49d3f3bd50d2
- 탭  sticky 미적용 상태
- 현재 로딩 중 스켈레톤 UI가 미적용
- 방장이 아닌 모임 탈퇴 기능 백엔드 수정 필요
- 신청서 목록은 디자이너와 상의 후 수정 예정
- 훅으로 분리하기
```useEffect(() => {
if (inView && hasNextPage && !isFetchingNextPage) { …
```
> [Feature/issue-185] 모임 관리 페이지 신청목록, 참가목록 구현

- package-lock.json
- package.json
- src/components/common/InfiniteList .tsx
- src/components/common/InfiniteReviewList.tsx
- src/components/pages/main/MainPerformanceSkeletonCard.tsx
- src/components/pages/main/MainTopFavoritesPerformances.tsx
- src/components/pages/main/MainTopGroupsPerformances.tsx
- src/components/pages/main/PerformanceWrapper.tsx
- src/components/pages/notifications/NotificationCard.tsx
- src/components/pages/notifications/NotificationCardSkeleton.tsx
- src/components/pages/notifications/NotificationList.tsx
- src/components/pages/reviews/managements/ReviewWriteModal.tsx
- src/components/pages/reviews/managements/WritableReviews.tsx
- src/components/pages/reviews/managements/WrittenReviews.tsx
- src/hooks/notificationHooks/notificationHooks.ts
- src/hooks/performanceHooks/performanceHooks.ts
- src/hooks/reviewHooks/reviewHooks.ts
- src/services/reviewsService.ts
- src/types/notification.ts
- src/types/reviews.ts
- 신규 기능 추가: suspensive 라이브러리 도입, 무한 스크롤 관련 공통 컴포넌트 제작
- 버그 수정: 무한 스크롤 pending상태일 때 스크롤을 움직이면 중복 호출이 되던 오류 해결
- 리펙토링: suspensive를 통해 pending 및 error상태를 관리하도록 리팩토링
- suspensive 라이브러리 도입
- tanstack-query를 사용할 때 pending, error등 상태 관리 코드가 복잡해지는 경우가 자주 발생
- 무한스크롤 관련 로직이 대부분 비슷하여 비슷한 코드를 여러번 중복해서 만들게 됨
- suspensive 라이브러리를 사용하여 같은 depth에서 로딩 및 에러 상태를 관리하도록 변경
- 무한 스크롤을 더 편리하게 사용할 수 있도록 suspensive의 ```SuspenseInfiniteQuery```를 사용하는 컴포넌트를 생성
- 동작은 변함이 없습니다.
- 현재 제가 만든 페이지들에만 적용되어있습니다
- 적용된 페이지: 메인 페이지, 알림 페이지, 리뷰 관리 페이지
- 무한 스크롤용으로 만든 ```<InfiniteList>```컴포넌트에 대한 사용방법 문서는 작성 예정입니다
close: #311
> [Feature/issue-311] suspensive 라이브러리 도입

- src/components/pages/NotificationToast.tsx
- 신규 기능 추가: 
- 버그 수정: 메인 페이지에서 로그인 무한루프 수정
- 리펙토링:
- 문서 업데이트:
- 기타:
- ```<NotificationToast>```에서 ```useGetNewNotificationsCheck```부분이 로그인이 안되었더라도 무조건 실행되어 오류 발생
- 로그인이 안되어 있을 경우 렌더링이 안되도록 변경
- 동작
- 특이 사항
close: #331
> [Fix/issue-331] 메인 페이지에서 로그인 무한루프 수정

- package-lock.json
- package.json
- src/components/common/TabBar/TabBar.tsx
- 신규 기능 추가: 현재 라우팅 경로에 따른 TabBar 선택적 렌더링 구현
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- TabBar가 렌더링 되지 않는 페이지들이 있는데, 해당 페이지마다 라우팅 그룹을 통해 폴더구조를 변경할 경우 폴더구조가 너무 난잡해짐
- 따라서 사용되지 않는 경로를 설정하여 해당 경로일 경우 TabBar가 렌더링되지 않도록 구현
- usePathname으로 현재 경로를 가져온 뒤 path-to-regexp라이브러리를 이용하여 해당 경로가 INVISIBLE_ROUTE인지 확인
- 만약 INVISIBLE_ROUTE에 포함될 경우 TabBar를 제외하고 children만 렌더링하도록 변경
- 동작
- 특이 사항
close: #339
> [Feature/issue-339] 현재 라우팅 경로에 따른 TabBar 선택적 렌더링 구현

- src/components/common/Toast/Toast.test.tsx
- src/components/common/Toast/Toast.tsx
- src/components/pages/performanceDetail/CreateGroupButton.tsx
- src/components/pages/performanceDetail/PerformanceDetailSummary.tsx
- src/components/pages/performanceDetail/PerformanceDetailWrapper.tsx
- src/mocks/handlers/performancesHandlers.ts
- 신규 기능 추가: 모임 개설 버튼 생성
- 기타: Toast 컴포넌트 디자인 적용
- 공연 상세 페이지에 모임 개설 버튼 생성
- Toast 컴포넌트 type별 디자인 적용
- 모임 개설 버튼 (`CreateGroupButton`)
- 모임 개설 페이지로 라우팅되는 버튼 컴포넌트 생성
- 공연 상세 조회 요청이 성공했을 경우에만 동작하도록 설정
- `Toast` 컴포넌트
- 디자인 적용
- 토스트 type별 아이콘 추가
- 테스트 코드 수정
https://github.com/user-attachments/assets/981d596c-b4d2-4ff2-8515-0ffebabd0194
- Toast 아이콘 추후 변경 필요
close: #335
> [Feature/issue-335] 모임 개설 버튼 생성, Toast 컴포넌트 디자인 적용

- src/components/common/GlobalNavigationBar/GlobalNavigationBar.tsx
- src/components/common/Header/Header.tsx
- src/components/common/Notification/Notification.tsx
- src/components/common/SearchInput/SearchInput.tsx
- src/lib/apiFetcher.ts
- src/stores/sseStore.ts
- src/utils/getNewAccessToken.ts
- 신규 기능 추가: 액세스 토큰 재발급 로직 함수로 분리
- 버그 수정:
- 리펙토링: unread-exists api관련 중복 호출 수정
- 문서 업데이트:
- 기타:
- 액세스 토큰을 재발급 받아 사용하는 로직이 여러곳에서 사용됨
- 해당 로직을 함수로 분리하여 재사용할 수 있도록 변경
- Header는 필요한 페이지마다 새로 렌더링 되기 때문에 unread-exists가 useEffect로 인해 중복 호출되는 오류 발생
- 액세스 토큰 재발급 로직을 함수로 분리
- Notification 컴포넌트를 화면 크기에 따라 서로 다른 컴포넌트가 렌더링 되도록 변경
- 데스크톱 환경일때는 GNB에서 사용될것이므로 useEffect로 pathName이 변할때마다 refetch
- 모바일 환경에서는 Header가 필요한 페이지마다 렌더링 될것이므로 useEffect와 refetch를 사용하지 않음
close: #347
> [Feature/issue-347] 액세스 토큰 재발급 로직 함수로 분리

- src/components/pages/groupDetail/Chat/Chat.tsx
- src/components/pages/groupDetail/Chat/ChatArea.tsx
- src/components/pages/groupDetail/Chat/ChatMessageInput.tsx
- src/hooks/chatHooks/chatHooks.ts
- src/mocks/handlers/usersHandlers.ts
- 리팩토링: 모임 내 채팅 에러 핸들링 추가
- userId 조회 시 에러 핸들링 추가
- 채팅 탭 Skeleton UI 적용
- 채팅방 에러 핸들링
- userId 조회
- isPending 일 경우 Skeleton UI가 나타나도록 설정
- isError이거나 userId가 없는 경우 접근 권한 오류 메세지 띄움
- 채팅방 에러 핸들링
- 채팅방 입장(웹소켓 연결) 시 액세스 토큰 확인 (유틸 함수 사용)
- 새 액세스 토큰으로 재시도 후에도 에러 시 에러 메세지 띄움
- 채팅 탭 Skeleton UI 적용
- userId 조회 시 스켈레톤 ui 적용
- 채팅방 연결중인 경우 연결중 메세지 띄움
- 액세스 토큰 만료됐을 경우 재발급 후 재시도
https://github.com/user-attachments/assets/9ba59357-6ca6-4b52-9d47-7ebedc7df3a4
- 액세스 토큰, 재발급한 액세스 토큰 모두 오류가 있을 때
https://github.com/user-attachments/assets/eb96ac3a-ae94-4a94-a3f7-dca409b75a35
close: #196
> [Refactor/issue-196] 모임 내 채팅 에러 핸들링

- src/components/common/Toast/Toast.test.tsx
- src/components/common/Toast/Toast.tsx
- src/components/icons/WarningIcon.tsx
- src/components/pages/groupDetail/GroupInfo.tsx
- src/components/pages/groupDetail/GroupInfoCard/GroupInfoCard.tsx
- src/components/pages/groupDetail/GroupModal/GroupModal.tsx
- src/components/pages/groupDetail/GroupTabs.tsx
- src/components/pages/groupDetail/GroupWrapper.tsx
- src/components/pages/performanceDetail/GroupApplyModal.tsx
- src/components/pages/performanceDetail/PerformanceDetailGroupsList.tsx
- src/constants/queryKeys.ts
- src/hooks/groupHooks/groupHooks.ts
- src/services/groupsService.ts
- src/types/group.ts
- src/types/toastContent.ts
- 신규 기능 추가: 모임 상세 내 모임 기본 정보 섹션 구현
- 모임 기본 정보 조회 api 연결
- 모임 기본 정보 섹션 디자인 적용
- 모임 기본 정보 조회 api 연결
- isError일 경우 '존재하지 않는 모임입니다' 메세지 띄움
- 모임 기본 정보 섹션 구현
- `GroupInfoCard`: 모임 기본 정보 컴포넌트 생성
- `GroupModal`: 모임 신청/탈퇴 모달 컴포넌트 생성
- Skeleton UI 적용
- 디자인 적용
- `ToastContent` 타입: toast 메세지와 toast 타입을 정의하는 타입 선언
- `Toast` 컴포넌트 type별 아이콘 수정
https://github.com/user-attachments/assets/89777921-795b-4deb-aba4-e0089d55fba3
- 모임 탈퇴 안되는 버그 수정 필요
- 모임 신청 status를 받아오지 않아 신청이 완료된 후 처리(버튼 disabled)를 할 수 없음
- 모임 참가자가 아닌 경우 블러 처리된 모임원 목록, 모임 탭이 보이도록 처리 필요
close: #360
> [Feature/issue-360] 모임 기본 정보 조회

- src/components/pages/groupDetail/Chat/Chat.tsx
- src/components/pages/groupDetail/Chat/ChatArea.tsx
- src/components/pages/groupDetail/Chat/ChatDateDivider.tsx
- src/components/pages/groupDetail/Chat/ChatInfo.tsx
- src/components/pages/groupDetail/Chat/ChatMessage.tsx
- src/components/pages/groupDetail/Chat/ChatMessageList.tsx
- src/components/pages/groupDetail/GroupTabs.tsx
- src/components/pages/groupDetail/GroupWrapper.tsx
- src/components/pages/groupDetail/PostNotice/PostNotice.tsx
- src/hooks/chatHooks/chatHooks.ts
- src/mocks/browser.ts
- src/mocks/handlers/chatHandlers.ts
- src/services/chatService.ts
- src/types/chat.ts
- src/utils/date.ts
- 신규 기능 추가: 채팅방 메세지 목록 조회 
- 채팅방 메세지 목록 조회 api
- 채팅창에 모임 기본 정보, 고정된 게시글 api 연결
- 채팅창 디자인 일부 수정
- 로딩 ui, 에러 핸들링
- 채팅방 메세지 목록 조회 api
- 무한 스크롤
- 내가 채팅 보냈을 때 맨 아래로 스크롤되도록 설정
- 추후 Suspensive 라이브러리로 리팩토링 필요
- msw handler 설정
- 채팅창에 모임 기본 정보, 고정된 게시글 api 연결
- 채팅창 디자인 일부 수정
- `formatToKST` 유틸 함수 추가
- 한국 시간(2025-06-18T15:00:43Z)을 `오전/오후 hh:mm` 형식으로 포맷하는 함수
- 로딩 ui, 에러 핸들링
- 채팅 연결 시 로딩, 무한 스크롤 시 로딩 ui 적용
https://github.com/user-attachments/assets/67bf27d8-5b2f-4445-9f60-30002be3fef0
- Suspensive 라이브러리 사용하여 무한스크롤 리팩토링 필요
close: #355
> [Feature/issue-355] 채팅방 메세지 목록 조회

- src/components/common/MessageInput/MessageInput.tsx
- src/components/common/TextareaInput/TextareaInput.tsx
- src/components/pages/groupDetail/CommentItem/CommentItem.tsx
- src/components/pages/groupDetail/CommentList/CommentList.tsx
- src/components/pages/groupDetail/PostDetailWrapper.tsx
- 리팩토링: 기존 채팅 메시지 인풋 컴포넌트의 재사용성을 높이고, 댓글 수정 기능을 개선했습니다.
- 기존 채팅 메시지 인풋 컴포넌트 재사용 컴포넌트로 분리: 여러 페이지에서 사용되는 채팅 메시지 입력 필드를 재사용 가능한 컴포넌트로 분리하여 코드 중복을 줄이고 유지보수성을 높였습니다.
- 페이지 내 댓글 수정 기능 모달로 변경: 기존 댓글 수정 방식이 사용자 경험을 저해하는 부분이 있어, 모달(Modal) 형태로 변경하여 더욱 직관적이고 편리하게 댓글을 수정할 수 있도록 개선했습니다.
- 채팅 메시지 입력 관련 UI 및 로직을 [MessageInput]으로 분리.
- 댓글 수정 시 [기존 방식 설명] 대신 모달을 띄우는 로직 구현.
- 모달 내에서 댓글 내용을 입력하고 수정할 수 있는 UI 구현.
- 댓글 수정 완료 시 모달이 닫히고 변경된 내용이 즉시 반영되도록 구현.
https://github.com/user-attachments/assets/780abc04-5d30-4c6b-8b00-744eee44a9c3
- 기존 채팅에서 사용하던 메시지인풋을 'MessageInput'으로 추가생성해 욕설방지와 토스트 기능 추가한 새로운 컴포넌트를 생성하였으니 적용하면 좋을 듯 합니다.
> [Feature/issue-372] 댓글 수정 모달 디자인으로 변경

- src/components/pages/groupDetail/Chat/ChatArea.tsx
- src/components/pages/groupDetail/GroupMembers.tsx
- src/components/pages/groupDetail/GroupWrapper.tsx
- src/components/pages/groupDetail/Members/MemberCard.tsx
- src/components/pages/groupDetail/Members/MemberDeleteModal.tsx
- src/components/pages/groupDetail/Members/MemberRoleModal.tsx
- src/components/pages/groupDetail/Members/MembersHeader.tsx
- src/components/pages/groupDetail/Members/MembersList.tsx
- src/constants/queryKeys.ts
- src/constants/roleLabels.ts
- src/hooks/groupHooks/groupHooks.ts
- src/mocks/handlers/groupsHandlers.ts
- src/services/groupsService.ts
- src/types/enums.ts
- src/types/group.ts
- 신규 기능 추가: 모임원 목록 조회, 역할 변경, 퇴출 기능 추가
- 버그 수정: 채팅창 버그 수정
- 모임원 목록 조회, 역할 변경, 퇴출 기능 추가
- 모임원 목록 조회, 역할 변경, 퇴출 api 연결
- 채팅창 버그 수정
- 모임원 목록 조회
- api 연결
- Carousel용 일반 호출 hook 추가
- InfiniteList용 무한스크롤 option, hook 추가
- Suspensive 라이브러리 사용
- 로딩 시 스켈레톤 ui 적용
- 사용자 프로필 사진이나 이름 클릭 시 프로필 페이지로 라우팅
- 모임원 역할 변경
- api 연결
- 모임장일 경우에만 모임장 위임 가능
- 모임장 본인은 역할 변경 불가능
- 모임원 퇴출
- api 연결
- 모임장일 경우에만 모임원 퇴출 가능
- 모임장 본인은 퇴출 불가능
- 채팅창 버그 수정
- 이전 채팅 메세지가 없을 경우 채팅 입력이 안되는 버그 수정
https://github.com/user-attachments/assets/eb31afdd-147c-48ce-a02b-a6935802a481
https://github.com/user-attachments/assets/a077978f-8098-4728-96af-963b03521ba2
https://github.com/user-attachments/assets/3f33459f-461b-4a07-8227-09615fda05fa
close: #383
> [Feature/issue-383] 모임원 목록 조회, 역할 변경, 퇴출

- src/components/common/MessageInput/MessageInput.tsx
- src/components/common/TabBar/TabBar.tsx
- src/components/icons/EditIcon.tsx
- src/components/pages/groupDetail/GroupInfoCard/GroupInfoCard.tsx
- src/components/pages/groupDetail/GroupModal/GroupModal.tsx
- src/components/pages/groupDetail/GroupPosts.tsx
- src/components/pages/groupDetail/PinCheckbox/PinCheckbox.tsx
- src/components/pages/groupDetail/PostCard/PostCard.tsx
- src/components/pages/groupDetail/PostDetailWrapper.tsx
- src/components/pages/groupDetail/PostEditWrapper.tsx
- src/components/pages/groupDetail/PostFormWrapper.tsx
- src/components/pages/groupDetail/PostImageUploader/PostImageUploader.tsx
- src/components/pages/groupDetail/PostNotice/PostNotice.tsx
- src/components/pages/groupDetail/editGroup/EditGroupWrapper.tsx
- src/components/pages/groupDetail/editGroup/NormalLocationSelector.tsx
- src/components/pages/groupDetail/editGroup/NormalTagInput.tsx
- src/utils/date.ts
- 신규 기능 추가: 모임 정보 수정 기능 개선, 게시글 기능 개선, 프로필 페이지 이동 기능 추가, 게시글 작성/수정 시 상단 고정 체크 기능 등
- 리팩토링: 게시글 작성, 수정시 기존 이미지 업로드 훅 사용
- 스타일 수정: 주석 제거, 스타일 클래스 조정, 하단 탭바 제거
- 기타: 미사용 import 정리, 컴포넌트 props 추가
- 해시태그 입력 UX 개선 (엔터 키 지원)
- 모임 수정 시 변경사항 없을 경우 버튼 비활성화 처리
- 모임 수정 시 지역 초기화 시 기존 선택값 표시
- 게시글 목록에 상단공지글 추가
- 댓글 입력창 고정 위치를 위한 props 추가
- 모임정보, 게시글에서 프로필 클릭 시 상세 페이지 이동 가능하도록 UX 개선
- 불필요한 코드(주석, 미사용 import) 제거 및 스타일 정리
- 게시글 작성, 수정시 기존 이미지 업로드 훅 재사용
- 게시글 작성/수정 시 상단 고정 체크 기능 추가
- 모임 정보 수정 화면에 해시태그 입력 기능 개선 (Enter 입력 대응)
- 수정 버튼: 변경 사항 없을 경우 disabled 처리
- 지역 초기화 버튼 클릭 시 기존 지역 값 복구
- 댓글 고정을 위한 className props 추가
- 프로필 영역 클릭 시 프로필 페이지로 라우팅
- 게시글 목록 탭에 상단 공지 추가
- 하단 탭바 제거 및 관련 컴포넌트 스타일 정리
- 미사용 import 및 주석 정리
- 게시글 작성, 수정시 useImageUploader 사용, 기존 이미지와 새로 추가된 이미지 판별하는 로직 추가
- 게시글 작성/수정 시 상단 고정 체크하는 컴포넌트 추가 …
> [Feature/issue-418] 모임 정보, 게시글 관련 기능 추가 및 리팩토링

- src/components/common/MessageInput/MessageInput.tsx
- src/components/common/TabBar/TabBar.tsx
- src/components/icons/EditIcon.tsx
- src/components/pages/groupDetail/GroupInfoCard/GroupInfoCard.tsx
- src/components/pages/groupDetail/GroupModal/GroupModal.tsx
- src/components/pages/groupDetail/GroupPosts.tsx
- src/components/pages/groupDetail/PinCheckbox/PinCheckbox.tsx
- src/components/pages/groupDetail/PostCard/PostCard.tsx
- src/components/pages/groupDetail/PostDetailWrapper.tsx
- src/components/pages/groupDetail/PostEditWrapper.tsx
- src/components/pages/groupDetail/PostFormWrapper.tsx
- src/components/pages/groupDetail/PostImageUploader/PostImageUploader.tsx
- src/components/pages/groupDetail/PostNotice/PostNotice.tsx
- src/components/pages/groupDetail/editGroup/EditGroupWrapper.tsx
- src/components/pages/groupDetail/editGroup/NormalLocationSelector.tsx
- src/components/pages/groupDetail/editGroup/NormalTagInput.tsx
- src/utils/date.ts
* chore: 주석 삭제
* style: 공지글 w-full 추가
* feat: 모임 정보에서 탈퇴 클릭 시 뒤로가기 추가
* feat: 프로필 클릭 시 프로필 페이지로 이동
* feat: 모임 정보 수정시 엔터로 해시태그 입력 추가
* feat: 모임 수정 시 지역 초기화 클릭하면 기존 지역으로 표시
* feat: 모임 수정 시 수정사항 없으면 버튼 disabled
* style: 하단 탭바 삭제, 주석 삭제, 아이콘 컴포넌트 수정
* feat: 댓글 하단 fix를 위한 className props추가
* feat: 하단 탭바 INVISIBLE에 게시글 수정 페이지 추가
* feat: 게시글 목록 탭에 공지 추가
* chore: 미사용 import 삭제
* feat: 모임 수정 시 지역선택에서 전체 제외
* style: 캐러셀에 세로크기가 다른 이미지들 가운데 정렬
* refactor: 이미지 업로드 useImageUploader 훅 사용으로 변경
* feat: 게시글 작성, 수정시 상단 고정 체크 기능 추가
- 신규 기능 추가: 
- 버그 수정:
- 리펙토링:
- 문서 업데이트:
- 기타:
- 이유
- 작업 내역
- 동작
- 특이 사항
close: #
> [Feature/issue-418] 모임 정보, 게시글 관련 기능 추가 및 리팩토링 (#428)

- src/components/pages/groupDetail/GroupBlurredContainer.tsx
- src/components/pages/groupDetail/GroupInfoCard/GroupInfoCard.tsx
- src/components/pages/groupDetail/GroupWrapper.tsx
- src/components/pages/groupsManagement/AppliedGroups.tsx
- 신규 기능 추가: 모임 상세페이지 모임원 목록, 모임 탭 블러 처리
- 모임 상세페이지: 사용자 경험 개선, 디자인 수정
- 나의 모임 페이지: 사용자 경험 개선, 불필요한 console 제거
- 모임 상세 페이지
- 모임 참가자가 아닐 경우 모임원 목록, 모임 탭 안 블러 처리
- 모임 정보와 모임원 목록 사이 갭 조정
- 모임 정보 카드 [카테고리 - 날짜 - 신고버튼] align 맞춤
- 나의 모임 페이지
- 신청한 모임에서 뜨는 console.log 삭제 (`AppliedGroups.tsx`)
- 신청한 모임 클릭 시 해당 모임 페이지로 이동
https://github.com/user-attachments/assets/6f36edcb-b85f-4c53-b7e9-9a81feed1a7a
close: #425
> [Feature/issue 425] 모임 상세페이지 모임원 목록, 모임 탭 블러 처리

- src/app/(hasGNB)/performances/[performanceId]/createGroup/page.tsx
- src/components/common/BottomSheetModal/BottomSheetContent.tsx
- src/components/common/Calendar/Calendar.tsx
- src/components/common/Form/FormText.tsx
- src/components/common/Toast/Toast.tsx
- src/components/common/TwoButtonModal/TwoButtonModal.style.ts
- src/components/pages/createGroup/CategorySelector.tsx
- src/components/pages/createGroup/DateSelector.tsx
- src/components/pages/createGroup/FormActions.tsx
- src/components/pages/createGroup/LocationSelector.tsx
- src/components/pages/createGroup/TagInput.tsx
- src/components/pages/favorite/FavoriteTabContainer.tsx
- src/hooks/useStyles/useStyles.tsx
- src/schema/groupsCreate.ts
- src/services/groupsService.ts
- src/types/group.ts
-   버그 수정: 모임 개설 API 스펙과 프론트엔드 데이터 불일치 문제를 해결했습니다.
-   리펙토링: 모임 개설 페이지의 전반적인 스타일링을 개선하고 사용자 경험을 향상시켰습니다.
-   **API 스펙 동기화**: 모임 개설 시 전달되는 `category` 값이 백엔드 API 명세와 달라 정상적으로 모임이 생성되지 않는 문제가 있었습니다. 이를 해결하기 위해 프론트엔드에서 사용하는 상수 값을 API 명세에 맞게 수정했습니다.
-   **사용자 피드백 강화**: 모임 개설 과정에서 사용자가 현재 상태를 명확히 인지할 수 있도록 피드백 메커니즘이 부족했습니다. 폼 제출 시, 태그 중복 입력 시 등 다양한 상황에 맞는 토스트 메시지를 추가하여 사용자 경험을 개선했습니다.
-   **UI 일관성 및 스타일 개선**: 모임 개설 페이지 내 컴포넌트들의 스타일이 일관되지 않고, 일부 UI가 사용자에게 혼동을 줄 수 있었습니다. `Calendar`, `DateSelector`, `LocationSelector` 등의 UI를 직관적으로 개선하고 전체적인 디자인 통일성을 높였습니다.
-   `CategorySelector`가 API 명세에 정의된 `GroupCategoryLabels` 상수를 사용하도록 수정했습니다.
-   `FormActions` 컴포넌트에 모임 생성 진행, 성공, 실패 상태를 알려주는 토스트 메시지 기능을 추가했습니다.
-   `TagInput` 컴포넌트에 중복된 태그 입력 시 에러 토스트가 표시되도록 개선했습니다.
-   `DateSelector`의 날짜 선택 로직을 개선하고, 날짜 범위가 …
> [Bug/issue-438] 모임 개설 api 스펙과 불일치 해결 및 스타일링 개선
